### ISSUE TITLE
Fitur Login

### ISSUE THREAD

**Issue by arrikur** [apap-ekstensi-2018/TA_A#6]
**Initial Page:** /login
**Form Request:** POST, /login
**Response Page:** /
**Role:** Mahasiswa & Pegawai

Pada fitur ini anda diminta untuk membuat sistem login dengan menggunakan username dan
password yang ada di database. Pada halaman “/login” akan terdapat form untuk mengisi
username dan password dari pengguna dan pengguna dapat mengklik submit untuk
memasukkan data untuk diverifikasi.

Jika tombol submit diklik, maka sistem akan melakukan validasi dengan Web Security. Jika
terverifikasi, maka sistem akan menampilkan halaman utama berdasarkan role pengguna.
Dan jika gagal diverifikasi, maka akan kembali ke halaman login.

**Comment by muhammadnuim** [comment]
sessionnya juga langsung di set kan bang ?

**Comment by arrikur** [comment]
@muhammadnuim belum ketauan im, loginnya pake bawaan spring kayaknya. Samain aja kaya tutorial 8 sepertinya.

**Comment by arrikur** [comment]
kerjain yang lowongan dulu aja @muhammadnuim
